In [ ]:
# Code to generate one million random well site samples from each basin simulated by the Rutherford et al. model for Sherwin et al. 2023

In [ ]:
# Mount Google Drive

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Import packages

import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

In [ ]:
# Set path to Basin-specific Rutherford simulation results

Rutherford_path = '/content/drive/MyDrive/Distributionpaper/RutherfordSiteResults/'

In [ ]:
# Import simulation results results for a given basin
# Modulate the selectedbasin number to select one basin at a time

basins = ['APPALACHIAN', 'DENVER-JULESBURG', 'FORT WORTH', 'PERMIAN', 'SAN JOAQUIN', 'UINTA']
columns_Rutherford = ['Tranche', 'Site emissions [kg/d]', 'Wells per site', 'Gas productivity [mscf/site/day]', 'Gas productivity [kg/d]', 'Fractional loss rate', 'Oil productivity [bbl/d]']
selectedbasin = basins[0] # 0, 1, 2, 3, 4, 5
iteration = 1
selectedResults = pd.read_csv(Rutherford_path + 'sitedata_' + selectedbasin + str(iteration) + '.csv', header=None)
selectedResults.columns = columns_Rutherford
selectedResults

,Tranche,Site emissions [kg/d],Wells per site,Gas productivity [mscf/site/day],Gas productivity [kg/d],Fractional loss rate,Oil productivity [bbl/d]
0,1,1.24090,1,2.737900e-02,0.27194,4.562900e+00,9.900000e-07
1,1,1.09040,1,8.706400e-01,8.64780,1.260900e-01,9.900000e-07
2,1,0.87950,1,4.106800e-02,0.40792,2.156100e+00,9.900000e-07
3,1,0.53746,1,8.898000e-01,8.83820,6.081100e-02,9.900000e-07
4,1,1.54350,1,2.190300e-02,0.21756,7.094700e+00,9.900000e-07
...,...,...,...,...,...,...,...
5982,73,135.15000,8,9.900000e-07,0.00001,1.374400e+07,3.148500e+00
5983,73,3.00860,1,9.900000e-07,0.00001,3.059600e+05,5.201900e-02
5984,73,6.62370,1,9.900000e-07,0.00001,6.735900e+05,3.310100e+00
5985,73,11.95200,1,9.900000e-07,0.00001,1.215500e+06,2.187500e+00
5986,73,58.68700,7,9.900000e-07,0.00001,5.968100e+06,8.498300e+00

In [ ]:
# Import the full 100 Monte Carlo realizations for the selected basin

selectedResults = pd.read_csv(Rutherford_path + 'sitedata_' + selectedbasin + str(iteration) + '.csv', header=None)
selectedResults.columns = columns_Rutherford
selectedResults['Iteration'] = 1
columns_Rutherford = ['Tranche', 'Site emissions [kg/d]', 'Wells per site', 'Gas productivity [mscf/site/day]', 'Gas productivity [kg/d]', 'Fractional loss rate', 'Oil productivity [bbl/d]']
number_iterations = 100
for jj in np.arange(1, number_iterations):
  selectedResultsTemp = pd.read_csv(Rutherford_path + 'sitedata_' + selectedbasin + str(jj+1) + '.csv', header=None)
  selectedResultsTemp.columns = columns_Rutherford
  selectedResultsTemp['Iteration'] = jj + 1
  selectedResults = selectedResults.append(selectedResultsTemp, ignore_index=True)
selectedResults

,Tranche,Site emissions [kg/d],Wells per site,Gas productivity [mscf/site/day],Gas productivity [kg/d],Fractional loss rate,Oil productivity [bbl/d],Iteration
0,1,1.24090,1,2.737900e-02,0.27194,4.562900e+00,9.900000e-07,1
1,1,1.09040,1,8.706400e-01,8.64780,1.260900e-01,9.900000e-07,1
2,1,0.87950,1,4.106800e-02,0.40792,2.156100e+00,9.900000e-07,1
3,1,0.53746,1,8.898000e-01,8.83820,6.081100e-02,9.900000e-07,1
4,1,1.54350,1,2.190300e-02,0.21756,7.094700e+00,9.900000e-07,1
...,...,...,...,...,...,...,...,...
632694,73,11.62300,1,9.900000e-07,0.00001,1.182000e+06,1.341500e+00,100
632695,73,20.18500,1,9.900000e-07,0.00001,2.052700e+06,1.286800e-01,100
632696,73,21.28700,1,9.900000e-07,0.00001,2.164700e+06,3.367600e-01,100
632697,73,27.11800,1,9.900000e-07,0.00001,2.757700e+06,6.023300e-02,100
632698,73,115.75000,9,9.900000e-07,0.00001,1.177100e+07,1.312300e+01,100

In [ ]:
# Generate 1 million randomly-sampled rows from the combined data frame for emissions and production

samples_to_export = selectedResults.loc[:, ['Site emissions [kg/d]', 'Gas productivity [mscf/site/day]']].sample(1000000, replace=True)
samples_to_export.to_csv(Rutherford_path + 'Rutherford_million_samples_' + selectedbasin + '_20220917.csv', index=False)

In [ ]:
# Compute total emissions, production by iteration

max_emission_size_kgh = np.inf #30 #100000000
max_emission_size_kgd = max_emission_size_kgh*24
totals = pd.DataFrame({'Emissions':np.sum(selectedResults.loc[(selectedResults['Iteration']==1) & (selectedResults['Site emissions [kg/d]']<=max_emission_size_kgd), 'Site emissions [kg/d]']),
                       'Production':np.sum(selectedResults.loc[(selectedResults['Iteration']==1) & (selectedResults['Site emissions [kg/d]']<=max_emission_size_kgd), 'Gas productivity [mscf/site/day]'])}, index=[0])

for jj in np.arange(1, number_iterations):
  totals = totals.append(pd.DataFrame({'Emissions':np.sum(selectedResults.loc[(selectedResults['Iteration']==jj) & (selectedResults['Site emissions [kg/d]']<=max_emission_size_kgd), 'Site emissions [kg/d]']),
                       'Production':np.sum(selectedResults.loc[(selectedResults['Iteration']==jj) & (selectedResults['Site emissions [kg/d]']<=max_emission_size_kgd), 'Gas productivity [mscf/site/day]'])}, index=[0]),
                       ignore_index=True)
totals

       Emissions     Production
0   35674.703769  370062.900393
1   35674.703769  370062.900393
2   44001.021005  383409.248465
3   36029.503321  406028.440517
4   53989.141133  357020.750545
..           ...            ...
95  33207.218283  350929.441486
96  39207.988460  400042.395649
97  39939.066863  355016.267536
98  42541.450410  395164.381325
99  28331.847584  368045.396794

[100 rows x 2 columns]

In [ ]:
# Make a histogram

from numpy.lib.histograms import histogram
#
mean_totals = np.mean(totals)
# histogram(totals.iloc[:,0]/mean_totals.iloc[0]), histogram(totals.iloc[:,1]/mean_totals.iloc[1])
np.append(mean_totals, np.std(1 - totals/mean_totals))

array([3.99173998e+04, 3.80230480e+05, 1.69227774e-01, 4.74831887e-02])

In [ ]:
# Compute average number of wells per site by basin (as a cross-check)

np.mean(selectedResults['Wells per site'])

1.7099473841431707